version: "3.1"
services: 
  example:
    image: node:10
    volumes: ["./:/home/node/app"]
    working_dir: '/home/node/app'
    command: bash -c "npm i && npm run build && npm run example"
    ports: ["9000:8000"]

